
(function(){
  const E=s=>typeof escapeHtml==='function'?escapeHtml(String(s??'')):String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const M=n=>typeof money2==='function'?money2(n):('$'+Number(n||0).toFixed(2));
  function nextMonth(m){const [y,mo]=m.split('-').map(Number);return new Date(Date.UTC(y,mo,1)).toISOString().slice(0,10);}
  window.renderFinancesPage=async function(){
    const main=document.querySelector('main'); if(!main)return;
    const {data:props,error}=await sb.from('properties').select('id,name').order('name');
    if(error){main.innerHTML='<div class="panel"><b>Could not load properties.</b><br>'+E(error.message)+'</div>';return;}
    const month=new Date().toISOString().slice(0,7);
    const opts=(props||[]).map(p=>'<option value="'+p.id+'">'+E(p.name)+'</option>').join('');
    main.innerHTML='<div class="pageHead"><div><h1>CPA-Ready Financial System</h1><p class="muted">Organize JGAP transactions for bookkeeping, reconciliation, tax review and CPA year-end work.</p></div><button class="secondary" onclick="render()">← Dashboard</button></div>'+
    '<div class="grid" id="financeStats"><div class="card"><div class="muted">Income</div><div class="metric">$0</div><div class="muted">Selected period</div></div><div class="card"><div class="muted">Expenses</div><div class="metric">$0</div><div class="muted">Selected period</div></div><div class="card"><div class="muted">Net Cash Flow</div><div class="metric">$0</div><div class="muted" id="financeNetNote">Selected period</div></div><div class="card"><div class="muted">Unreconciled</div><div class="metric">0</div><div class="muted">Needs review</div></div></div>'+
    '<div class="panel" style="margin:16px 0"><div class="sectionTitle">Bookkeeping Controls</div><div class="formGrid"><label>Month<input id="financeMonth" type="month" value="'+month+'" onchange="loadTransactions()"></label><label>Property Filter<select id="financePropertyFilter" onchange="loadTransactions()"><option value="">All Properties + Company</option>'+opts+'</select></label><label>Reconciliation<select id="financeReconFilter" onchange="loadTransactions()"><option value="">All</option><option value="false">Unreconciled</option><option value="true">Reconciled</option></select></label><label>Tax Treatment<select id="financeTaxFilter" onchange="loadTransactions()"><option value="">All</option><option value="deductible">Deductible</option><option value="capital">Capital / Asset</option><option value="personal">Personal / Non-business</option><option value="review">CPA Review</option></select></label></div><div id="financeBreakdown" style="margin-top:14px"></div></div>'+
    '<div class="panel" style="margin:16px 0"><div class="sectionTitle">Add Transaction</div><div class="formGrid"><label>Date<input id="f_date" type="date" value="'+new Date().toISOString().slice(0,10)+'"></label><label>Type<select id="f_type"><option value="expense">Expense</option><option value="income">Income</option></select></label><label>Property<select id="f_property"><option value="">Company / General</option>'+opts+'</select></label><label>Category<input id="f_category" placeholder="Rent, insurance, repairs, utilities..."></label><label>Vendor / Payee<input id="f_vendor" placeholder="Company or person"></label><label>Payment Method<input id="f_payment" placeholder="ACH, check, card, cash..."></label><label>Account<input id="f_account" placeholder="Operating checking, card..."></label><label>Tax Treatment<select id="f_tax"><option value="review">CPA Review</option><option value="deductible">Deductible</option><option value="capital">Capital / Asset</option><option value="personal">Personal / Non-business</option></select></label><label>Receipt / Reference<input id="f_receipt" placeholder="Invoice or receipt #"></label><label>Amount<input id="f_amount" type="number" step="0.01" value="0"></label></div><label>Description<input id="f_desc" placeholder="What was this transaction for?"></label><label>Notes<textarea id="f_notes" rows="2" placeholder="Bookkeeping or CPA notes"></textarea></label><div id="financeMsg"></div><button class="primary" onclick="saveTransaction()">Save Transaction</button></div>'+
    '<div class="panel" style="margin:16px 0"><div class="sectionTitle">CPA Export</div><p class="muted">Download the selected month as a CSV ledger for your bookkeeper or CPA.</p><button class="primary" onclick="exportFinanceCSV()">Download CPA CSV</button></div><div id="transactionsList" class="panel">Loading transactions...</div>';
    loadTransactions();
  };
  window.saveTransaction=async function(){
    const msg=document.getElementById('financeMsg'), amount=Number(document.getElementById('f_amount')?.value)||0;
    if(amount<=0){msg.innerHTML='<div class="error">Enter an amount greater than 0.</div>';return;}
    const payload={p_property_id:document.getElementById('f_property')?.value||null,p_transaction_date:document.getElementById('f_date')?.value,p_category:document.getElementById('f_category')?.value.trim()||'General',p_description:document.getElementById('f_desc')?.value.trim()||null,p_amount:amount,p_transaction_type:document.getElementById('f_type')?.value||'expense'};
    const {error}=await sb.rpc('create_current_user_transaction',payload);
    if(error){msg.innerHTML='<div class="error">'+E(error.message)+'</div>';return;}
    const {data:last}=await sb.from('financial_transactions').select('id').order('created_at',{ascending:false}).limit(1).maybeSingle();
    if(last?.id) await sb.from('financial_transactions').update({vendor_name:document.getElementById('f_vendor')?.value.trim()||null,payment_method:document.getElementById('f_payment')?.value.trim()||null,account_name:document.getElementById('f_account')?.value.trim()||null,tax_treatment:document.getElementById('f_tax')?.value||'review',receipt_reference:document.getElementById('f_receipt')?.value.trim()||null,notes:document.getElementById('f_notes')?.value.trim()||null}).eq('id',last.id);
    msg.innerHTML='<div class="success">Transaction saved.</div>'; ['f_amount','f_desc','f_vendor','f_payment','f_account','f_receipt','f_notes'].forEach(id=>{const e=document.getElementById(id);if(e)e.value=id==='f_amount'?'0':'';}); loadTransactions();
  };
  window.loadTransactions=async function(){
    const wrap=document.getElementById('transactionsList');if(!wrap)return;
    const month=document.getElementById('financeMonth')?.value||new Date().toISOString().slice(0,7), property=document.getElementById('financePropertyFilter')?.value||'', recon=document.getElementById('financeReconFilter')?.value||'', tax=document.getElementById('financeTaxFilter')?.value||'';
    let q=sb.from('financial_transactions').select('id,transaction_date,category,description,amount,transaction_type,property_id,vendor_name,payment_method,account_name,tax_treatment,receipt_reference,reconciled,notes,properties(name)').gte('transaction_date',month+'-01').lt('transaction_date',nextMonth(month)).order('transaction_date',{ascending:false});
    if(property)q=q.eq('property_id',property);if(recon)q=q.eq('reconciled',recon==='true');if(tax)q=q.eq('tax_treatment',tax);
    const {data,error}=await q;if(error){wrap.innerHTML='<div class="error">'+E(error.message)+'</div>';return;}
    const rows=data||[], income=rows.filter(x=>x.transaction_type==='income').reduce((a,x)=>a+Number(x.amount||0),0), expenses=rows.filter(x=>x.transaction_type==='expense').reduce((a,x)=>a+Number(x.amount||0),0), unreconciled=rows.filter(x=>!x.reconciled).length;
    const cards=document.querySelectorAll('#financeStats .metric');if(cards.length){cards[0].textContent=M(income);cards[1].textContent=M(expenses);cards[2].textContent=M(income-expenses);cards[3].textContent=String(unreconciled);}
    const note=document.getElementById('financeNetNote');if(note)note.textContent=(income-expenses)>=0?'Positive recorded cash flow':'Negative recorded cash flow';
    const cats={};rows.forEach(x=>{const k=x.category||'Other';cats[k]=(cats[k]||0)+(x.transaction_type==='expense'?-1:1)*Number(x.amount||0);});
    const bd=document.getElementById('financeBreakdown');const entries=Object.entries(cats).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1]));
    if(bd)bd.innerHTML=entries.length?'<div class="sectionTitle">Category Breakdown</div><div style="overflow:auto"><table class="table"><thead><tr><th>Category</th><th>Net</th><th>Direction</th></tr></thead><tbody>'+entries.map(([k,v])=>'<tr><td>'+E(k)+'</td><td>'+M(Math.abs(v))+'</td><td>'+(v>=0?'Income':'Expense')+'</td></tr>').join('')+'</tbody></table></div>':'<div class="empty">No transactions recorded for '+E(month)+' yet.</div>';
    if(!rows.length){wrap.innerHTML='<div class="sectionTitle">Transaction History</div><p class="muted">No transactions recorded for the selected filters.</p>';return;}
    wrap.innerHTML='<div class="sectionTitle">Transaction History</div><div style="overflow:auto"><table class="table"><thead><tr><th>Date</th><th>Property</th><th>Category</th><th>Vendor / Payee</th><th>Type</th><th>Tax</th><th>Reconciled</th><th>Amount</th><th></th></tr></thead><tbody>'+rows.map(x=>'<tr><td>'+E(x.transaction_date)+'</td><td>'+E(x.properties?.name||'Company / General')+'</td><td>'+E(x.category||'')+'</td><td>'+E(x.vendor_name||'—')+'</td><td>'+E(x.transaction_type)+'</td><td>'+E(x.tax_treatment||'review')+'</td><td><input type="checkbox" '+(x.reconciled?'checked':'')+' onchange="toggleFinanceReconciled(\''+x.id+'\',this.checked)"></td><td>'+M(x.amount)+'</td><td><button class="secondary" onclick="viewFinanceTransaction(\''+x.id+'\')">Details</button></td></tr>').join('')+'</tbody></table></div>';
  };
  window.toggleFinanceReconciled=async function(id,value){const {error}=await sb.from('financial_transactions').update({reconciled:!!value}).eq('id',id);if(error)alert(error.message);else loadTransactions();};
  window.viewFinanceTransaction=async function(id){const {data:x,error}=await sb.from('financial_transactions').select('*,properties(name)').eq('id',id).maybeSingle();if(error||!x){alert(error?.message||'Transaction not found.');return;}alert(['Date: '+x.transaction_date,'Type: '+x.transaction_type,'Property: '+(x.properties?.name||'Company / General'),'Category: '+x.category,'Vendor: '+(x.vendor_name||'—'),'Payment: '+(x.payment_method||'—'),'Account: '+(x.account_name||'—'),'Tax treatment: '+(x.tax_treatment||'review'),'Receipt/reference: '+(x.receipt_reference||'—'),'Description: '+(x.description||'—'),'Notes: '+(x.notes||'—'),'Amount: '+M(x.amount),'Reconciled: '+(x.reconciled?'Yes':'No')].join('\n'));};
  window.exportFinanceCSV=async function(){
    const month=document.getElementById('financeMonth')?.value||new Date().toISOString().slice(0,7),property=document.getElementById('financePropertyFilter')?.value||'';
    let q=sb.from('financial_transactions').select('transaction_date,transaction_type,category,description,amount,vendor_name,payment_method,account_name,tax_treatment,receipt_reference,reconciled,notes,properties(name)').gte('transaction_date',month+'-01').lt('transaction_date',nextMonth(month)).order('transaction_date');
    if(property)q=q.eq('property_id',property);const {data,error}=await q;if(error){alert(error.message);return;}
    const headers=['Date','Type','Property','Category','Description','Vendor/Payee','Payment Method','Account','Tax Treatment','Receipt/Reference','Reconciled','Amount','Notes'];
    const csv=[headers,...(data||[]).map(x=>[x.transaction_date,x.transaction_type,x.properties?.name||'Company / General',x.category,x.description||'',x.vendor_name||'',x.payment_method||'',x.account_name||'',x.tax_treatment||'review',x.receipt_reference||'',x.reconciled?'Yes':'No',x.amount,x.notes||''])].map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n');
    const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='JGAP_CPA_Ledger_'+month+'.csv';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);
  };
})();