const JGAP_LEARNING_BOOK_OUTLINE=[
['Part 1 — Real Estate Foundations','Understanding How Real Estate Investing Works'],['Part 1 — Real Estate Foundations','Types of Real Estate Investments'],['Part 1 — Real Estate Foundations','Gross Rent'],['Part 1 — Real Estate Foundations','Vacancy'],['Part 1 — Real Estate Foundations','Operating Expenses'],['Part 1 — Real Estate Foundations','NOI'],['Part 1 — Real Estate Foundations','Debt Service'],['Part 1 — Real Estate Foundations','Cash Flow'],['Part 1 — Real Estate Foundations','Cap Rate'],['Part 1 — Real Estate Foundations','Cash-on-Cash Return'],['Part 1 — Real Estate Foundations','DSCR'],
['Part 2 — Finding Deals','Where to Find Properties'],['Part 2 — Finding Deals','Finding Off-Market Deals'],['Part 2 — Finding Deals','Working With Realtors'],['Part 2 — Finding Deals','Analyzing Multifamily Properties'],['Part 2 — Finding Deals','Deal Radar'],['Part 2 — Finding Deals','Evaluating Asking Prices'],['Part 2 — Finding Deals','Making an Offer'],
['Part 3 — Analyzing a Deal','Reading the Numbers'],['Part 3 — Analyzing a Deal','Building a Pro Forma'],['Part 3 — Analyzing a Deal','Understanding Financing'],['Part 3 — Analyzing a Deal','Rehab Costs'],['Part 3 — Analyzing a Deal','Holding Costs'],['Part 3 — Analyzing a Deal','Due Diligence'],['Part 3 — Analyzing a Deal','Identifying Red Flags'],['Part 3 — Analyzing a Deal','Deal Analyzer Walkthrough'],
['Part 4 — Buying & Closing','Getting Financing'],['Part 4 — Buying & Closing','Working With Lenders'],['Part 4 — Buying & Closing','Inspections'],['Part 4 — Buying & Closing','Appraisals'],['Part 4 — Buying & Closing','Closing'],['Part 4 — Buying & Closing','What Happens After Closing'],
['Part 5 — Managing the Investment','Property Management'],['Part 5 — Managing the Investment','Tenants'],['Part 5 — Managing the Investment','Leases'],['Part 5 — Managing the Investment','Rent Collection'],['Part 5 — Managing the Investment','Repairs & Maintenance'],['Part 5 — Managing the Investment','Contractors'],['Part 5 — Managing the Investment','Keeping Financial Records'],
['Part 6 — Growing the Business','Scaling From One Property to Multiple Properties'],['Part 6 — Growing the Business','Multifamily Investing'],['Part 6 — Growing the Business','Reinvesting Cash Flow'],['Part 6 — Growing the Business','Partnerships'],['Part 6 — Growing the Business','Building Business Systems'],['Part 6 — Growing the Business','Moving Into Other Investments'],
['Part 7 — Advanced Investing','Refinancing'],['Part 7 — Advanced Investing','BRRRR'],['Part 7 — Advanced Investing','House Flipping'],['Part 7 — Advanced Investing','Value-Add Investing'],['Part 7 — Advanced Investing','Commercial Real Estate'],['Part 7 — Advanced Investing','Laundromat & Other Business Investments']
];
async function ensureLearningBookOutline(){
 const {data:{user}}=await sb.auth.getUser();if(!user)return;
 const {data:existing}=await sb.from('learning_book_chapters').select('chapter_number').eq('user_id',user.id);
 const have=new Set((existing||[]).map(x=>Number(x.chapter_number)));
 const missing=JGAP_LEARNING_BOOK_OUTLINE.map((x,i)=>({user_id:user.id,chapter_number:i+1,part_title:x[0],chapter_title:x[1]})).filter(x=>!have.has(x.chapter_number));
 if(missing.length){const r=await sb.from('learning_book_chapters').insert(missing);if(r.error)console.warn('Learning book outline setup:',r.error);}
 await seedLearningBookLessons(user.id);
}

const JGAP_LEARNING_BOOK_LESSON_CONTENT={
3:{source:"Lesson 2 - Understanding Rental Property Numbers.docx",title:"Gross Rent",html:`<h3>Lesson: Understanding Rental Property Numbers</h3><p><b>Gross rent</b> is the total rental income a property would generate before subtracting vacancy or operating expenses.</p><h4>Example</h4><p>A four-unit property with each unit renting for $1,000 produces $4,000/month, or $48,000/year in gross scheduled rent.</p><p>The lesson emphasizes that gross rent is only the beginning. It does not account for vacancy, repairs, taxes, insurance, management, or the mortgage.</p><h4>Investor Questions</h4><ul><li>What are the current rents?</li><li>What could the units reasonably rent for?</li><li>Are rents below market?</li><li>Are there additional income opportunities?</li></ul>`},
4:{source:"Lesson 2 - Understanding Rental Property Numbers.docx",title:"Vacancy",html:`<h3>Lesson: Vacancy</h3><p>A rental property is not necessarily occupied 100% of the time. Tenants move out, units need repairs, leasing can take time, and collections can be imperfect.</p><h4>Example</h4><p>Gross rent of $48,000 with a 5% vacancy assumption produces $2,400 of vacancy and $45,600 of effective rental income.</p><p>The lesson's purpose is to avoid pretending that every scheduled dollar of rent will be collected.</p>`},
5:{source:"Lesson 2 - Understanding Rental Property Numbers.docx",title:"Operating Expenses",html:`<h3>Lesson: Operating Expenses</h3><p>Operating expenses are the costs associated with running and maintaining the property.</p><ul><li>Property taxes</li><li>Insurance</li><li>Repairs and maintenance</li><li>Property management</li><li>Owner-paid utilities</li><li>Landscaping and pest control</li><li>Accounting and legal expenses</li><li>Administrative and common-area expenses</li></ul><h4>Example</h4><p>The lesson's four-unit example uses $17,500 of annual operating expenses. Effective rental income of $45,600 less $17,500 produces $28,100 of NOI.</p>`},
6:{source:"Lesson 2 - Understanding Rental Property Numbers.docx",title:"NOI",html:`<h3>Lesson: Net Operating Income (NOI)</h3><p><b>NOI</b> tells us how much income the property produces from its operations before debt service and income taxes.</p><p><b>Formula:</b> Gross Rent − Vacancy/Credit Loss − Operating Expenses = NOI</p><h4>Example</h4><p>$48,000 Gross Rent − $2,400 Vacancy − $17,500 Operating Expenses = <b>$28,100 NOI</b>.</p><p>NOI is a property-level operating measure. It is not the same as the owner's cash flow after the mortgage.</p>`},
7:{source:"Lesson 2 - Understanding Rental Property Numbers.docx",title:"Debt Service",html:`<h3>Lesson: Debt Service</h3><p>Debt service is the required payment on the property's loan. In the lesson's simplified example, annual mortgage debt service is $18,000.</p><p>With $28,100 NOI and $18,000 of debt service, $10,100 remains as annual cash flow before taxes, or approximately $842/month.</p><p>The lesson also stresses asking how much will be borrowed, what interest rate can be obtained, what the monthly payment will be, and what annual debt service will be.</p>`},
8:{source:"Lesson 11 — Cash Flow.docx",title:"Cash Flow",html:`<h3>Lesson 11 — Cash Flow</h3><p>Cash flow is the money remaining from property operations after operating expenses and debt service have been paid.</p><p><b>Formula:</b> NOI − Debt Service = Cash Flow Before Taxes</p><h4>Important distinction</h4><p>Gross rent is not cash flow, and NOI is not cash flow. Debt service is what separates NOI from cash flow.</p><h4>Cash-Flow Waterfall</h4><ol><li>Calculate Gross Rental Income.</li><li>Subtract Vacancy.</li><li>Calculate Effective Gross Income.</li><li>Subtract Operating Expenses.</li><li>Calculate NOI.</li><li>Subtract Debt Service.</li><li>Calculate Cash Flow Before Taxes.</li></ol><p>The lesson also introduces cash-flow sensitivity and reserves as important considerations.</p>`},
9:{source:"Lesson 13 — Cap Rate(1).docx",title:"Cap Rate",html:`<h3>Lesson 13 — Cap Rate</h3><p>Cap rate measures the relationship between a property's Net Operating Income (NOI) and its price or value.</p><p><b>Formula:</b> Cap Rate = NOI ÷ Property Price × 100</p><h4>Example</h4><p>$30,000 NOI ÷ $300,000 price = 10% cap rate.</p><p>Cap rate looks at unlevered property performance. It does not ask how much cash remains after the mortgage; that is a cash-flow and cash-on-cash question.</p><h4>Cap Rate vs. Cash-on-Cash</h4><p>Cap Rate measures NOI relative to property price/value. Cash-on-Cash Return measures annual cash flow relative to investor cash invested.</p><h4>Underwriting caution</h4><p>The lesson stresses that cap rate is only as good as the NOI behind it. If NOI is overstated, the cap rate is overstated. Investors should calculate and review their own NOI rather than simply accepting a seller's NOI.</p><h4>Current vs. Pro Forma vs. Stabilized</h4><p>Current cap rate uses current operating performance. Pro forma cap rate uses projected future NOI. Stabilized cap rate uses a reasonably supportable stabilized NOI and depends on successfully achieving that projected performance.</p>`},
10:{source:"Lesson 12 — Cash-on-Cash Return(1).docx",title:"Cash-on-Cash Return",html:`<h3>Lesson 12 — Cash-on-Cash Return</h3><p>Cash-on-cash return measures annual cash flow generated by an investment compared with the amount of cash the investor has invested.</p><p><b>Formula:</b> Annual Cash Flow ÷ Total Cash Invested × 100</p><h4>Example</h4><p>$10,000 annual cash flow ÷ $100,000 total cash invested = 10% cash-on-cash return.</p><p>The lesson explains that this measurement helps investors understand the relationship between capital invested and annual cash flow, which matters because investors have limited capital.</p>`},
11:{source:"Lesson 14 — DSCR(1).docx",title:"DSCR",html:`<h3>Lesson 14 — DSCR</h3><p><b>DSCR — Debt Service Coverage Ratio</b> answers a practical question: Does the property's NOI provide enough income to cover its annual debt service?</p><p><b>Formula:</b> DSCR = NOI ÷ Annual Debt Service</p><h4>Debt Service</h4><p>For this lesson, annual debt service is treated as annual principal plus interest payments.</p><h4>Coverage Example</h4><p>If a property produces $100,000 NOI and requires $80,000 annual debt service, $100,000 ÷ $80,000 = <b>1.25x</b>. The property produces 1.25 times the amount needed to cover its annual debt service.</p>`},
15:{source:"Lesson 7 - RENT COMPS.docx",title:"Rent Comps",html:`<h3>Lesson 7 — Rent Comps</h3><p>Rent comps are comparable rental properties used as evidence about what a property can reasonably rent for.</p><h4>Three Rent Numbers</h4><ul><li><b>Current Rent:</b> what the property is actually receiving today.</li><li><b>Market Rent:</b> what comparable properties indicate the property could reasonably rent for today, assuming similar characteristics and condition.</li><li><b>Stabilized Rent:</b> a reasonably supportable rent level expected after the property reaches a sustainable operating condition.</li></ul><p><b>A comp is evidence, not an automatic answer.</b> Similar properties can differ in location, unit type, size, condition, amenities, utilities, parking, age, and tenant market.</p><h4>Why It Matters</h4><p>Rent assumptions affect gross income, NOI, cash flow, property value, financing analysis, and offer price.</p><h4>Stabilized Rent Discipline</h4><p>Stabilized rent is not whatever number produces the desired cash flow. It needs evidence. The lesson presents a rent ladder from current rent to current market/as-is, renovated rent, and stabilized rent.</p>`},
19:{source:"Lesson 6 - READING REAL ESTATE LISTINGS.docx",title:"Reading Real Estate Listings",html:`<h3>Lesson 6 — Reading Real Estate Listings</h3><p><b>A listing is the beginning of the investigation—not the conclusion.</b> Listing information may be incomplete, rounded, estimated, outdated, selectively presented, based on seller information, or based on public records. It should not automatically be treated as verified underwriting data.</p><h4>The Three-Column Method</h4><ul><li><b>Facts:</b> information directly stated in the listing.</li><li><b>Claims:</b> statements that require verification, such as “below-market rents” or “huge upside.”</li><li><b>Missing Information:</b> underwriting inputs not provided, such as actual expenses, taxes, insurance, utilities, repairs, management, rent roll, lease terms, and collections.</li></ul><h4>Investor Workflow</h4><ol><li>Extract the property facts.</li><li>Identify claims.</li><li>Identify missing information.</li><li>Request documentation.</li><li>Verify income and expenses.</li><li>Research comparable rents and sales.</li><li>Inspect the property.</li><li>Underwrite the deal.</li><li>Determine maximum price/terms based on your criteria.</li><li>Decide whether the opportunity deserves an offer or further investigation.</li></ol><h4>FACT — ASSUMPTION — VERIFY</h4><p>The lesson recommends putting these three words at the top of every underwriting file. It also warns against underwriting from a best-case scenario and recommends thinking in conservative, base, and upside cases.</p>`}};
async function seedLearningBookLessons(userId){
 const rows=Object.entries(JGAP_LEARNING_BOOK_LESSON_CONTENT).map(([chapter_number,v])=>({user_id:userId,chapter_number:Number(chapter_number),content_html:v.html,source_file_name:v.source}));
 const {data:existing}=await sb.from('learning_book_chapters').select('chapter_number,content_html').eq('user_id',userId);
 const have=new Map((existing||[]).map(x=>[Number(x.chapter_number),x]));
 const missingContent=rows.filter(r=>{const c=have.get(r.chapter_number);return !c || !c.content_html || !c.content_html.trim();});
 if(missingContent.length){const r=await sb.from('learning_book_chapters').upsert(missingContent,{onConflict:'user_id,chapter_number'});if(r.error)console.warn('Learning book lesson import:',r.error);}
}

async function renderLearningBookPage(){
 const {data:{user}}=await sb.auth.getUser();if(!user){authView();return;}
 shell();const main=document.querySelector('.layout>main');if(!main)return;
 main.innerHTML='<div class="pageHead"><div><h1>📚 JGAP Real Estate Investor\'s Learning Book</h1><div class="muted">Build your real estate education book one chapter at a time.</div></div><div class="toolbar"><button class="secondary" onclick="printLearningBook()">🖨️ Print</button><button class="secondary" onclick="downloadLearningBook()">⬇️ Download</button><button class="primary" onclick="emailLearningBook()">✉️ Email</button></div></div><div class="panel" style="margin-bottom:16px;background:#f8fbff"><b>How we will build it</b><span class="muted"> Your uploaded files can be added to the appropriate chapters without changing the original files. We can expand and polish the book as you upload more material.</span></div><div class="detailGrid" style="grid-template-columns:310px minmax(0,1fr)"><div class="panel" style="padding:14px"><div class="sectionTitle">Book Outline</div><input id="learningBookSearch" placeholder="Search chapters..." oninput="filterLearningBookChapters()"><div id="learningBookList"><div class="muted">Loading book...</div></div></div><div class="panel"><div id="learningBookEditor"><div class="muted">Select a chapter.</div></div></div></div>';
 window.__learningBookChapters=[];await ensureLearningBookOutline();
 const {data,error}=await sb.from('learning_book_chapters').select('id,chapter_number,part_title,chapter_title,content_html,source_file_name,updated_at').eq('user_id',user.id).order('chapter_number');
 if(error){document.getElementById('learningBookList').innerHTML='<div class="error">Unable to load the learning book: '+escapeHtml(error.message)+'</div>';return;}
 window.__learningBookChapters=data||[];filterLearningBookChapters();const firstPopulated=window.__learningBookChapters.find(c=>c.content_html&&c.content_html.trim());const firstChapter=firstPopulated||window.__learningBookChapters[0];if(firstChapter)selectLearningBookChapter(firstChapter.id);
}
function filterLearningBookChapters(){
 const q=(document.getElementById('learningBookSearch')?.value||'').toLowerCase().trim(),host=document.getElementById('learningBookList');if(!host)return;
 const rows=(window.__learningBookChapters||[]).filter(c=>(c.part_title+' '+c.chapter_title).toLowerCase().includes(q));let lastPart='';
 host.innerHTML=rows.map(c=>{const part=c.part_title!==lastPart?'<div class="muted" style="font-size:11px;font-weight:800;text-transform:uppercase;margin:12px 4px 5px">'+escapeHtml(c.part_title)+'</div>':'';lastPart=c.part_title;return part+'<button type="button" class="secondary" data-book-chapter="'+c.id+'" style="display:block;width:100%;text-align:left;margin:4px 0;white-space:normal"><b>Chapter '+c.chapter_number+'</b><div>'+escapeHtml(c.chapter_title)+'</div></button>';}).join('')||'<div class="muted">No chapters found.</div>';
 host.querySelectorAll('[data-book-chapter]').forEach(b=>b.addEventListener('click',()=>selectLearningBookChapter(b.dataset.bookChapter)));
}
function selectLearningBookChapter(id){
 const c=(window.__learningBookChapters||[]).find(x=>x.id===id);if(!c)return;window.__learningBookCurrentId=id;const e=document.getElementById('learningBookEditor');if(!e)return;
 e.innerHTML='<div class="pageHead" style="margin-bottom:12px"><div><div class="muted">Chapter '+c.chapter_number+' • '+escapeHtml(c.part_title)+'</div><h2 style="margin:4px 0">'+escapeHtml(c.chapter_title)+'</h2></div><span class="muted" style="font-size:12px">Last saved '+new Date(c.updated_at).toLocaleString()+'</span></div><label style="font-weight:700;font-size:13px">Chapter content</label><div id="learningBookContent" contenteditable="true" spellcheck="true" style="min-height:560px;border:1px solid #ccd5e2;border-radius:9px;padding:20px;background:#fff;outline:none;line-height:1.7;font-size:16px">'+(c.content_html||'')+'</div><div style="display:flex;justify-content:space-between;gap:12px;align-items:center;margin-top:12px;flex-wrap:wrap"><span id="learningBookSaveStatus" class="muted" style="font-size:12px">Edit this chapter and save when ready.</span><button class="primary" onclick="saveLearningBookChapter()">Save Chapter</button></div>';
}
async function saveLearningBookChapter(){
 const id=window.__learningBookCurrentId,content=document.getElementById('learningBookContent')?.innerHTML||'';if(!id)return;
 const {error}=await sb.from('learning_book_chapters').update({content_html:content,updated_at:new Date().toISOString()}).eq('id',id);if(error){alert('Could not save chapter: '+error.message);return;}
 const c=(window.__learningBookChapters||[]).find(x=>x.id===id);if(c){c.content_html=content;c.updated_at=new Date().toISOString();}const s=document.getElementById('learningBookSaveStatus');if(s)s.textContent='Saved '+new Date().toLocaleTimeString();
}
function learningBookPrintHtml(){
 const rows=(window.__learningBookChapters||[]).slice().sort((a,b)=>a.chapter_number-b.chapter_number);
 return '<!doctype html><html><head><meta charset="utf-8"><title>JGAP Real Estate Investor\'s Learning Book</title><style>body{font-family:Arial,sans-serif;max-width:850px;margin:40px auto;line-height:1.65;color:#172033}h1{text-align:center;margin-top:80px}h2{margin-top:55px;border-bottom:1px solid #ddd;padding-bottom:8px}.chapter{page-break-before:always}@media print{body{margin:0 30px}}</style></head><body><h1>JGAP Real Estate Investor\'s Learning Book</h1><p style="text-align:center">JGAP Venture Group LLC</p>'+rows.map(c=>'<section class="chapter"><div class="muted">Chapter '+c.chapter_number+' • '+escapeHtml(c.part_title)+'</div><h2>'+escapeHtml(c.chapter_title)+'</h2>'+(c.content_html||'<p><em>This chapter has not been developed yet.</em></p>')+'</section>').join('')+'</body></html>';
}
function printLearningBook(){const w=window.open('','_blank');if(!w){alert('Please allow pop-ups for JGAP to print the book.');return;}w.document.write(learningBookPrintHtml());w.document.close();w.focus();setTimeout(()=>w.print(),300);}
function downloadLearningBook(){const blob=new Blob([learningBookPrintHtml()],{type:'text/html;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='JGAP-Real-Estate-Investors-Learning-Book.html';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}
function emailLearningBook(){const subject=encodeURIComponent("JGAP Real Estate Investor's Learning Book"),body=encodeURIComponent("I am sharing the JGAP Real Estate Investor's Learning Book.\\n\\nUse the JGAP app to download or print the current book.");window.location.href='mailto:?subject='+subject+'&body='+body;}
