const JGAP_LEARNING_BOOK_OUTLINE=[
['Part 1 — Real Estate Foundations','Understanding How Real Estate Investing Works'],['Part 1 — Real Estate Foundations','Types of Real Estate Investments'],['Part 1 — Real Estate Foundations','Gross Rent'],['Part 1 — Real Estate Foundations','Vacancy'],['Part 1 — Real Estate Foundations','Operating Expenses'],['Part 1 — Real Estate Foundations','NOI'],['Part 1 — Real Estate Foundations','Debt Service'],['Part 1 — Real Estate Foundations','Cash Flow'],['Part 1 — Real Estate Foundations','Cap Rate'],['Part 1 — Real Estate Foundations','Cash-on-Cash Return'],['Part 1 — Real Estate Foundations','DSCR'],
['Part 2 — Finding Deals','Where to Find Properties'],['Part 2 — Finding Deals','Finding Off-Market Deals'],['Part 2 — Finding Deals','Working With Realtors'],['Part 2 — Finding Deals','Analyzing Multifamily Properties'],['Part 2 — Finding Deals','Deal Radar'],['Part 2 — Finding Deals','Evaluating Asking Prices'],['Part 2 — Finding Deals','Making an Offer'],
['Part 3 — Analyzing a Deal','Reading the Numbers'],['Part 3 — Analyzing a Deal','Building a Pro Forma'],['Part 3 — Analyzing a Deal','Understanding Financing'],['Part 3 — Analyzing a Deal','Rehab Costs'],['Part 3 — Analyzing a Deal','Holding Costs'],['Part 3 — Analyzing a Deal','Due Diligence'],['Part 3 — Analyzing a Deal','Identifying Red Flags'],['Part 3 — Analyzing a Deal','Deal Analyzer Walkthrough'],
['Part 4 — Buying & Closing','Getting Financing'],['Part 4 — Buying & Closing','Working With Lenders'],['Part 4 — Buying & Closing','Inspections'],['Part 4 — Buying & Closing','Appraisals'],['Part 4 — Buying & Closing','Closing'],['Part 4 — Buying & Closing','What Happens After Closing'],
['Part 5 — Managing the Investment','Property Management'],['Part 5 — Managing the Investment','Tenants'],['Part 5 — Managing the Investment','Leases'],['Part 5 — Managing the Investment','Rent Collection'],['Part 5 — Managing the Investment','Repairs & Maintenance'],['Part 5 — Managing the Investment','Contractors'],['Part 5 — Managing the Investment','Keeping Financial Records'],
['Part 6 — Growing the Business','Scaling From One Property to Multiple Properties'],['Part 6 — Growing the Business','Multifamily Investing'],['Part 6 — Growing the Business','Reinvesting Cash Flow'],['Part 6 — Growing the Business','Partnerships'],['Part 6 — Growing the Business','Building Business Systems'],['Part 6 — Growing the Business','Moving Into Other Investments'],
['Part 7 — Advanced Investing','Refinancing'],['Part 7 — Advanced Investing','BRRRR'],['Part 7 — Advanced Investing','House Flipping'],['Part 7 — Advanced Investing','Value-Add Investing'],['Part 7 — Advanced Investing','Commercial Real Estate'],['Part 7 — Advanced Investing','Laundromat & Other Business Investments']
];
async function ensureLearningBookOutline(){
 const {data:{user}}=await sb.auth.getUser();if(!user)return;
 const {data:existing}=await sb.from('learning_book_chapters').select('chapter_number').eq('user_id',user.id);
 const have=new Set((existing||[]).map(x=>Number(x.chapter_number)));
 const missing=JGAP_LEARNING_BOOK_OUTLINE.map((x,i)=>({user_id:user.id,chapter_number:i+1,part_title:x[0],chapter_title:x[1]})).filter(x=>!have.has(x.chapter_number));
 if(missing.length){const r=await sb.from('learning_book_chapters').insert(missing);if(r.error)console.warn('Learning book outline setup:',r.error);}
}
async function renderLearningBookPage(){
 const {data:{user}}=await sb.auth.getUser();if(!user){authView();return;}
 shell();const main=document.querySelector('.layout>main');if(!main)return;
 main.innerHTML='<div class="pageHead"><div><h1>📚 JGAP Real Estate Investor\\'s Learning Book</h1><div class="muted">Build your real estate education book one chapter at a time.</div></div><div class="toolbar"><button class="secondary" onclick="printLearningBook()">🖨️ Print</button><button class="secondary" onclick="downloadLearningBook()">⬇️ Download</button><button class="primary" onclick="emailLearningBook()">✉️ Email</button></div></div><div class="panel" style="margin-bottom:16px;background:#f8fbff"><b>How we will build it</b><span class="muted"> Your uploaded files can be added to the appropriate chapters without changing the original files. We can expand and polish the book as you upload more material.</span></div><div class="detailGrid" style="grid-template-columns:310px minmax(0,1fr)"><div class="panel" style="padding:14px"><div class="sectionTitle">Book Outline</div><input id="learningBookSearch" placeholder="Search chapters..." oninput="filterLearningBookChapters()"><div id="learningBookList"><div class="muted">Loading book...</div></div></div><div class="panel"><div id="learningBookEditor"><div class="muted">Select a chapter.</div></div></div></div>';
 window.__learningBookChapters=[];await ensureLearningBookOutline();
 const {data,error}=await sb.from('learning_book_chapters').select('id,chapter_number,part_title,chapter_title,content_html,source_file_name,updated_at').eq('user_id',user.id).order('chapter_number');
 if(error){document.getElementById('learningBookList').innerHTML='<div class="error">Unable to load the learning book: '+escapeHtml(error.message)+'</div>';return;}
 window.__learningBookChapters=data||[];filterLearningBookChapters();if(window.__learningBookChapters.length)selectLearningBookChapter(window.__learningBookChapters[0].id);
}
function filterLearningBookChapters(){
 const q=(document.getElementById('learningBookSearch')?.value||'').toLowerCase().trim(),host=document.getElementById('learningBookList');if(!host)return;
 const rows=(window.__learningBookChapters||[]).filter(c=>(c.part_title+' '+c.chapter_title).toLowerCase().includes(q));let lastPart='';
 host.innerHTML=rows.map(c=>{const part=c.part_title!==lastPart?'<div class="muted" style="font-size:11px;font-weight:800;text-transform:uppercase;margin:12px 4px 5px">'+escapeHtml(c.part_title)+'</div>':'';lastPart=c.part_title;return part+'<button type="button" class="secondary" data-book-chapter="'+c.id+'" style="display:block;width:100%;text-align:left;margin:4px 0;white-space:normal"><b>Chapter '+c.chapter_number+'</b><div>'+escapeHtml(c.chapter_title)+'</div></button>';}).join('')||'<div class="muted">No chapters found.</div>';
 host.querySelectorAll('[data-book-chapter]').forEach(b=>b.addEventListener('click',()=>selectLearningBookChapter(b.dataset.bookChapter)));
}
function selectLearningBookChapter(id){
 const c=(window.__learningBookChapters||[]).find(x=>x.id===id);if(!c)return;window.__learningBookCurrentId=id;const e=document.getElementById('learningBookEditor');if(!e)return;
 e.innerHTML='<div class="pageHead" style="margin-bottom:12px"><div><div class="muted">Chapter '+c.chapter_number+' • '+escapeHtml(c.part_title)+'</div><h2 style="margin:4px 0">'+escapeHtml(c.chapter_title)+'</h2></div><span class="muted" style="font-size:12px">Last saved '+new Date(c.updated_at).toLocaleString()+'</span></div><label style="font-weight:700;font-size:13px">Chapter content</label><div id="learningBookContent" contenteditable="true" spellcheck="true" style="min-height:560px;border:1px solid #ccd5e2;border-radius:9px;padding:20px;background:#fff;outline:none;line-height:1.7;font-size:16px">'+(c.content_html||'')+'</div><div style="display:flex;justify-content:space-between;gap:12px;align-items:center;margin-top:12px;flex-wrap:wrap"><span id="learningBookSaveStatus" class="muted" style="font-size:12px">Edit this chapter and save when ready.</span><button class="primary" onclick="saveLearningBookChapter()">Save Chapter</button></div>';
}
async function saveLearningBookChapter(){
 const id=window.__learningBookCurrentId,content=document.getElementById('learningBookContent')?.innerHTML||'';if(!id)return;
 const {error}=await sb.from('learning_book_chapters').update({content_html:content,updated_at:new Date().toISOString()}).eq('id',id);if(error){alert('Could not save chapter: '+error.message);return;}
 const c=(window.__learningBookChapters||[]).find(x=>x.id===id);if(c){c.content_html=content;c.updated_at=new Date().toISOString();}const s=document.getElementById('learningBookSaveStatus');if(s)s.textContent='Saved '+new Date().toLocaleTimeString();
}
function learningBookPrintHtml(){
 const rows=(window.__learningBookChapters||[]).slice().sort((a,b)=>a.chapter_number-b.chapter_number);
 return '<!doctype html><html><head><meta charset="utf-8"><title>JGAP Real Estate Investor\\'s Learning Book</title><style>body{font-family:Arial,sans-serif;max-width:850px;margin:40px auto;line-height:1.65;color:#172033}h1{text-align:center;margin-top:80px}h2{margin-top:55px;border-bottom:1px solid #ddd;padding-bottom:8px}.chapter{page-break-before:always}@media print{body{margin:0 30px}}</style></head><body><h1>JGAP Real Estate Investor\\'s Learning Book</h1><p style="text-align:center">JGAP Venture Group LLC</p>'+rows.map(c=>'<section class="chapter"><div class="muted">Chapter '+c.chapter_number+' • '+escapeHtml(c.part_title)+'</div><h2>'+escapeHtml(c.chapter_title)+'</h2>'+(c.content_html||'<p><em>This chapter has not been developed yet.</em></p>')+'</section>').join('')+'</body></html>';
}
function printLearningBook(){const w=window.open('','_blank');if(!w){alert('Please allow pop-ups for JGAP to print the book.');return;}w.document.write(learningBookPrintHtml());w.document.close();w.focus();setTimeout(()=>w.print(),300);}
function downloadLearningBook(){const blob=new Blob([learningBookPrintHtml()],{type:'text/html;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='JGAP-Real-Estate-Investors-Learning-Book.html';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}
function emailLearningBook(){const subject=encodeURIComponent("JGAP Real Estate Investor's Learning Book"),body=encodeURIComponent("I am sharing the JGAP Real Estate Investor's Learning Book.\\n\\nUse the JGAP app to download or print the current book.");window.location.href='mailto:?subject='+subject+'&body='+body;}
