(function(){
const E=s=>typeof escapeHtml==='function'?escapeHtml(String(s??'')):String(s??'');
window.renderLendersPage=async function(){
const main=document.querySelector('main');if(!main)return;
main.innerHTML='<div class="pageHead"><div><h1>Lenders</h1><p class="muted">Build and manage JGAP relationships with lenders before the next acquisition.</p></div><button class="secondary" onclick="render()">← Dashboard</button></div>'+
'<div class="grid" id="lenderStats"><div class="card"><div class="muted">Lenders</div><div class="metric">0</div></div><div class="card"><div class="muted">Active Relationships</div><div class="metric">0</div></div><div class="card"><div class="muted">Follow-Ups Due</div><div class="metric">0</div></div></div>'+
'<div class="panel" style="margin:16px 0"><div class="sectionTitle">Add Lender</div><div class="formGrid"><label>Institution<input id="l_inst" placeholder="Bank, credit union, private lender..."></label><label>Contact Name<input id="l_contact"></label><label>Lender Type<select id="l_type"><option>Bank</option><option>Credit Union</option><option>Commercial Lender</option><option>Private Lender</option><option>Hard Money</option><option>Other</option></select></label><label>Status<select id="l_status"><option>Prospect</option><option>Contacted</option><option>Active Relationship</option><option>Past Relationship</option></select></label><label>Phone<input id="l_phone"></label><label>Email<input id="l_email" type="email"></label><label>Website<input id="l_web"></label><label>Address<input id="l_addr"></label><label>Loan Types<input id="l_loans" placeholder="SFR, multifamily, commercial..."></label><label>Minimum Loan<input id="l_min" type="number" step="1000"></label><label>Maximum Loan<input id="l_max" type="number" step="1000"></label><label>Typical LTV %<input id="l_ltv" type="number" step="0.1"></label><label>Typical DSCR<input id="l_dscr" type="number" step="0.01"></label><label>Last Contact<input id="l_last" type="date"></label><label>Next Follow-Up<input id="l_next" type="date"></label></div><label>Rate / Fee Notes<textarea id="l_rates" rows="2"></textarea></label><label>Term / Amortization / Recourse Notes<textarea id="l_terms" rows="2"></textarea></label><label>Notes<textarea id="l_notes" rows="2"></textarea></label><div id="l_msg"></div><button class="primary" onclick="saveLender()">Save Lender</button></div>'+
'<div class="panel"><div class="sectionTitle">Lender Directory</div><input id="l_search" placeholder="Search lenders..." oninput="loadLenders()" style="margin-bottom:12px"><div id="lenderList">Loading...</div></div>';loadLenders();};
window.saveLender=async function(){const v=id=>document.getElementById(id)?.value?.trim()||null;const p={company_id:null,institution_name:v('l_inst'),contact_name:v('l_contact'),lender_type:v('l_type'),phone:v('l_phone'),email:v('l_email'),website:v('l_web'),address:v('l_addr'),loan_types:v('l_loans'),minimum_loan_amount:Number(v('l_min'))||null,maximum_loan_amount:Number(v('l_max'))||null,typical_ltv:Number(v('l_ltv'))||null,typical_dscr:Number(v('l_dscr'))||null,rate_notes:v('l_rates'),term_notes:v('l_terms'),status:v('l_status')||'Prospect',last_contact_date:v('l_last'),next_follow_up_date:v('l_next'),notes:v('l_notes')};if(!p.institution_name){document.getElementById('l_msg').innerHTML='<div class="error">Enter the lender institution name.</div>';return;}const cid=await getCurrentCompanyId();if(!cid){document.getElementById('l_msg').innerHTML='<div class="error">Could not determine JGAP company.</div>';return;}p.company_id=cid;const {error}=await sb.from('lenders').insert(p);if(error){document.getElementById('l_msg').innerHTML='<div class="error">'+E(error.message)+'</div>';return;}document.getElementById('l_msg').innerHTML='<div class="success">Lender saved.</div>';loadLenders();};
window.loadLenders=async function(){const q=document.getElementById('l_search')?.value?.trim()||'';let query=sb.from('lenders').select('*').order('next_follow_up_date',{ascending:true,nullsFirst:false}).order('institution_name');if(q)query=query.or('institution_name.ilike.%'+q+'%,contact_name.ilike.%'+q+'%,lender_type.ilike.%'+q+'%');const {data,error}=await query;if(error){document.getElementById('lenderList').innerHTML='<div class="error">'+E(error.message)+'</div>';return;}const rows=data||[];const active=rows.filter(x=>x.status==='Active Relationship').length,today=new Date().toISOString().slice(0,10),due=rows.filter(x=>x.next_follow_up_date&&x.next_follow_up_date<=today).length;const cards=document.querySelectorAll('#lenderStats .metric');if(cards[0])cards[0].textContent=rows.length;if(cards[1])cards[1].textContent=active;if(cards[2])cards[2].textContent=due;document.getElementById('lenderList').innerHTML=rows.length?'<div style="overflow:auto"><table class="table"><thead><tr><th>Institution</th><th>Contact</th><th>Type</th><th>Loan Types</th><th>Max Loan</th><th>Status</th><th>Next Follow-Up</th></tr></thead><tbody>'+rows.map(x=>'<tr><td><b>'+E(x.institution_name)+'</b><br><span class="muted">'+E(x.phone||'')+'</span></td><td>'+E(x.contact_name||'')+'<br>'+E(x.email||'')+'</td><td>'+E(x.lender_type||'')+'</td><td>'+E(x.loan_types||'')+'</td><td>'+(x.maximum_loan_amount?'$'+Number(x.maximum_loan_amount).toLocaleString():'—')+'</td><td>'+E(x.status||'')+'</td><td>'+E(x.next_follow_up_date||'—')+'</td></tr>').join('')+'</tbody></table></div>':'<div class="empty">No lenders added yet.</div>';};
})();